---
- hosts: "WDC_n5ks"
  gather_facts: false

  tasks:
  - name: n9k-intdesc for WDC
    nxos_command:
      commands:
        - "sh int desc | i [Ww][Dd][Cc]"
    register: config
    tags: intdesc
  - name: save config to /etc/ansible/backups/intdescwdc
    copy:
      content: "{{config.stdout[0]}}"
      dest: "/etc/ansible/backups/intdescwdc/{{inventory_hostname}}.txt"
    tags: intdesc
...
