---
- hosts: "n9k-vnichange"
  gather_facts: false

  tasks:
  - name: New Description for TEMP VLANs
    nxos_vlan:
      vlan_id: "{{ item.id }}"
      name: "{{ item.name }}"
    with_items: "{{ VLANDESC }}"
  - name: New L2 VNI for the VLANs
    nxos_vlan:
      vlan_id: "{{ item.id }}"
      name: "{{ item.name }}"
      mapped_vni: "{{ item.vni }}"
    with_items: "{{ VNI }}"
  - name: Configure BUM for VTEP
    nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item.vni }}"
      multicast_group: "{{ item.multicast }}"
    with_items: 
    - "{{ VNI }}"
  - name: Save Config
    nxos_command:
      commands:
        - copy run start
...
